### ISSUE TITLE
cc_ari_contingency

### ISSUE THREAD

**Issue by PaolaTella** [CorradoLanera/CrossClustering#12]
- [x]  `cc_ari_contingency()` should return a list:

```
$ ari
$ conf_int
```
- [x] conf_int possibly with names `lower` and `upper`.

- [x] create class `ari` and print methods to render the output nicier with informative message (see details of the function)

- [x] include warning if `sum(mat) < 100` --- see details

**Comment by CorradoLanera** [comment]
- [x] return:
$ ari (with confidence interval as attributes)
$ input
$ partitions (created with function in #13)
$ p-values (ari and permutations)
