### ISSUE TITLE
naming convention and other syle

### ISSUE THREAD

**Issue by CorradoLanera** [CorradoLanera/CrossClustering#2]
- [x] snake_case
- [x] verb-like function names
- [x] final check on NEWS.md

**Comment by PaolaTella** [comment]
Ok, so I would change the names as follows:

- ARI_contingency becomes cc_get_ari_ct
- CrossClustering becomes cc
- max_proportion_function becomes cc_get_max_prop
- PermSignificanceARI becomes cc_test_perm_ari
- SignificanceARI becomes cc_test_ari
- which_cluster becomes cc_get_clusters

**Comment by CorradoLanera** [comment]
What's about, in order:
- cc_get_ari_contingency
- cc_eval_crossclustering
- cc_get_max_proportion
- cc_test_ari_permutation
- cc_test_ari_standard
- cc_get_cluster

**Comment by PaolaTella** [comment]
I would prefer:

- cc_get_ari_contingency
- cc_crossclustering
- cc_get_max_proportion
- cc_test_ari_permutation
- cc_test_ari
- cc_get_cluster

**Comment by CorradoLanera** [comment]
all done and tested
