### ISSUE TITLE
Test ARI_contingency

### ISSUE THREAD

**Issue by PaolaTella** [CorradoLanera/CrossClustering#7]
Please, test that the function ARI_contingency with the contingecy table of the paper of Steinley (2016) results with the same values (ARI =0.1176 [-0.41; 0.65]).

mat <- matrix(c(2, 1, 0, 0, 2, 1), ncol = 3, nrow = 2, byrow = TRUE)
ARI_contingency(mat, digits = 4)

**Comment by PaolaTella** [comment]
Also, I would like that this function gives also:
- an alert message if the total of the elements in the contingency table are less than 100;
- the contingency table;
- the interpretation like is written in the details;
- and the p-values of the two test implemented.

Do you think these things would be possible? Thanks.

**Comment by CorradoLanera** [comment]
test implemented and passed (with 4-digits precision CI [-.4107, 0.6460])
For the changes, yes it is possible. We have to decide only "how"

**Comment by CorradoLanera** [comment]
Test implemented, changes reported in #12
